extends:
  - "@35up/35up-base"
parserOptions:
  project:
    - tsconfig.json
overrides:
  -
    files:
      - "*.ts"
    rules:
      import/no-extraneous-dependencies:
        - error
        - peerDependencies: true
