name: ci-common

on:
  push:
    branches: [ master ]
    paths:
      - common/**
      - ./*
      - ./.github/workflows/ci-common.yml
  pull_request:
    branches: [ master ]
    paths:
      - common/**
      - ./*
      - ./.github/workflows/ci-common.yml

concurrency:
  group: ${{ github.base_ref }}-${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci-common:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: "./common"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Configure GitHub NPM Token
        run: npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:coverage
      - name: Generate jest-coverage-report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1
        with:
          working-directory: common
          skip-step: all
          coverage-file: coverage/report.json
          base-coverage-file: coverage/report.json
